{
 "title": "Cardinality Explorer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(cardinality_estimate,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cardinality_estimate{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "interval",
    "query": {
     "query": "label_values(cardinality_estimate,interval)"
    }
   },
   {
    "name": "group_by_keys",
    "query": {
     "query": "label_values(cardinality_estimate{interval=~\"$interval\", group_by_keys!=\"__global__\", group_by_keys!=\"__group__\"},group_by_keys)"
    }
   },
   {
    "name": "group_by_values",
    "query": {
     "query": "label_values(cardinality_estimate{interval=~\"$interval\", group_by_keys=~\"$group_by_keys\"},group_by_values)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Cardinality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",group_by_keys=~\"__global__\"}) by (interval)",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Group Keys Cardinality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_keys=~\"__group__\"}) by (interval,group_by_values)",
     "legendFormat": "{{group_by_values}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Group Cardinality Top 10",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_keys=~\"$group_by_keys\",group_by_values=~\"$group_by_values\"}) without (job,instance))",
     "legendFormat": "{{group_by_keys}}: {{group_by_values}} ({{interval}})"
    }
   ]
  }
 ]
}