{
 "title": "cestimator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"^cestimator.*\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\", version=~\"^cestimator.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RSS memory % usage ($instance)",
   "type": "timeseries",
   "description": "How much resident memory (RAM) the process is actually using, compared to its allowed container or system limit.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.\n\nClick on the line and choose Drilldown to show memory usage per instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\",instance=~\"$instance\"}\n) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n    /\n    process_cpu_cores_available{job=~\"$job\",instance=~\"$instance\"}\n) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_protoparser_read_calls_total{job=~\"$job\",instance=~\"$instance\",type=\"promremotewrite\"}[$__rate_interval])) by(job, type, net) > 0",
     "legendFormat": "{{net}}: {{ type }} ({{job}})"
    }
   ]
  },
  {
   "title": "Concurrent inserts ($instance)",
   "type": "timeseries",
   "description": "Shows how many concurrent inserts are taking place.\n\nIf the number of concurrent inserts hitting the `limit` or is close to the `limit` constantly - it might be a sign of a resource shortage.\n\n If vmagent's CPU usage and remote write connection saturation are at normal level, it might be that `-maxConcurrentInserts` cmd-line flag need to be increased.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(vm_concurrent_insert_current{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} ({{job}})"
    },
    {
     "expr": "min(vm_concurrent_insert_capacity{job=~\"$job\",instance=~\"$instance\"}) by(job)",
     "legendFormat": "limit ({{job}})"
    }
   ]
  },
  {
   "title": "Rows rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_protoparser_rows_read_total{job=~\"$job\",instance=~\"$instance\",type=\"promremotewrite\"}[$__rate_interval])) by(job, type) > 0",
     "legendFormat": "{{ type }} ({{job}})"
    }
   ]
  },
  {
   "title": "Rows error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_protoparser_read_errors_total{job=~\"cestimator\",type=\"promremotewrite\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ type }} ({{net}})"
    }
   ]
  },
  {
   "title": "Estimation samples rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cestorage_estimator_insert_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by(job, group_by_keys) > 0",
     "legendFormat": "{{ group_by_keys }} ({{job}})"
    }
   ]
  },
  {
   "title": "Group keys rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(cestorage_estimator_group_rejected_size{job=~\"$job\",instance=~\"$instance\"}) by(job,group_by_keys) > 0",
     "legendFormat": "{{ group_by_keys }} ({{job}})"
    }
   ]
  },
  {
   "title": "Group keys size %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    cestorage_estimator_group_size{job=~\"$job\",instance=~\"$instance\"}\n    /\n    cestorage_estimator_group_limit{job=~\"$job\",instance=~\"$instance\"}\n) by(job,group_by_keys)",
     "legendFormat": "{{ group_by_keys }} ({{job}})"
    }
   ]
  },
  {
   "title": "Throubleshouting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cardinality Estimates Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "topk(10, max(cardinality_estimate{job=~\"$job\",instance=~\"$instance\",interval=~\"$interval\",group_by_keys=~\"$group_by_keys\",group_by_values=~\"$group_by_values\"}) without (job,instance))",
       "legendFormat": "{{group_by_keys}}: {{group_by_values}} ({{interval}})"
      }
     ]
    },
    {
     "title": "Scrape cardinality response size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(cestorage_http_response_size_bytes_total{job=~\"$job\", instance=~\"$instance\", path=\"/cardinality/metrics\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Scrape cardinality metrics duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(cestorage_http_request_duration_seconds_total{job=~\"$job\", instance=~\"$instance\", path=\"/cardinality/metrics\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  { "title": "Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "RSS memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n) by(job,instance)",
     "legendFormat": "{{instance}}: ({{job}})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "max(\n    rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n) by(job,instance)",
     "legendFormat": "{{instance}}: ({{job}})"
    }
   ]
  }
 ]
}